### PR TITLE
[ODS-5747] WebAPI package metadata update

### PR DESCRIPTION
**Pull request by mjaksn**

### CODE REVIEW

**Comment by semalaiappan** [comment]
@mjaksn   https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.github/workflows/Publish%20to%20Azure%20Artifacts.yml#L6 Publish to Azure Artifacts workflow only publish SandboxAdmin,SwaggerUI,WebApi,Databases,EdFi.Ods.Api.Sdk,EdFi.SdkGen NugetPackages after "InitDev, Smoke Tests Sandbox, Year-Specific, and Shared Instance" workflow completes in main ,so for this story to validate we need to publish WebApi package from your working branch and execute the teamcity from your branch here in this build https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsApi_OdsApiDeployStagingAndSmokeTestSandbox?branch=&mode=builds so that you can validate the your code changes here https://api-stage.ed-fi.org/v7.0/api

**Comment by semalaiappan** [comment]
@mjaksn  What you can do is in this workflow https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.github/workflows/InitDev%2CUnit%20tests%2CIntegration%20tests%2CPackage.yml#L138  add  Install-credential-handler &  Publish to Azure Artifacts steps from here https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/4306402472/workflow#L38 .then finally run InitDev, Unit tests, Integration tests, Package workflow from your branch and once you see the new package version in Azure feeds and uncommit the changes in nitDev, Unit tests, Integration tests, Package workflow . Now you have new EdFi.Suite3.Ods.WebApi here   https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi/versions/7.0.1346 and then deploy from Teamcity

**Review by semalaiappan — CHANGES_REQUESTED** [review]
It requires to deploy and test from staging environment  for EdFi.Suite3.Ods.WebApi package to validate this code changes .  I have my instructions in PR comments

**Comment by mjaksn** [comment]
Thanks, @semalaiappan . I wasn't familiar with that process and didn't realize that was what was needed. I'll need to request access to TeamCity/stage, and once I have that, I will complete those steps.

**Review by semalaiappan — APPROVED** [review]
I am approving 7.0.1370 package version is deployed in staging and verified

**Pull request merged**
