### PR TITLE
[ODS-5364] Rename appsettings.development.json files to appsettings.Development.json

### PR DESCRIPTION
**Pull request by ericstockdale**

### CODE REVIEW

**Comment by semalaiappan** [comment]
@ericstockdale    Missing here in this file  https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.gitignore#L50

**Comment by semalaiappan** [comment]
@ericstockdale   Missing in this file https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/logistics/scripts/activities/build/CloudOds/PrepareDatabasesForExport.ps1#L58

**Review by semalaiappan — CHANGES_REQUESTED** [review]
Missing here in this file [https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.gitignore#L50](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.gitignore?rgh-link-date=2022-06-08T15%3A40%3A35Z#L50)
Missing in this file [https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/logistics/scripts/activities/build/CloudOds/PrepareDatabasesForExport.ps1#L58](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/logistics/scripts/activities/build/CloudOds/PrepareDatabasesForExport.ps1?rgh-link-date=2022-06-08T15%3A42%3A14Z#L58)

**Comment by semalaiappan** [comment]
@ericstockdale   Please rebase main with latest ,so that Standard pull Request will be green also

**Comment by ericstockdale** [comment]
@semalaiappan 

- Created an updated branch with the latest from main.
- Updated PrepareDatebaseForExport
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/ODS-5364/logistics/scripts/activities/build/CloudOds/PrepareDatabasesForExport.ps1#L58

- The .gitignore file was updated.  I think your link was referencing main not ODS-5364
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/ODS-5364/.gitignore#L50

**Review by semalaiappan — APPROVED** [review]

**Pull request merged**
