### PR TITLE
[ODS-4664] Dynamic Plugin Validation based on assemblyMetadata.json file in FindPluginAssemblies method 

### PR DESCRIPTION
**Pull request by semalaiappan**

### CODE REVIEW

**Review by gmcelhanon — CHANGES_REQUESTED** [review]
The builds on this PR are failing because you added the projects back into the solution. You need to fix this and make sure that the builds are running before moving to QA.

**Comment by semalaiappan** [comment]
@gmcelhanon -Build will fail actually . This is manual dynamic plugin .   I added all steps to show reviewer what are all code changes i did for this ticket
I will remove the manual sample profile project into ODS/API solution as soon as  get the changes and ran successfully . otherwise reviewer needs to do that again for this QA review
actually in another ticket https://tracker.ed-fi.org/browse/ODS-4644 where I am moving Sample.Profile project to \Ed-Fi-Extensions\Extensions\ and setup team city build for Sample.Profile Dynamic plugin

**Comment by semalaiappan** [comment]
@gmcelhanon  - I removed code changes related to Manual Steps

**Comment by semalaiappan** [comment]
@gmcelhanon  EdFi.Ods.Profiles.Sample (Packages) — TeamCity build is not applicable for this story , Please ignore it .

**Review by gmcelhanon — APPROVED** [review]

**Review by gmcelhanon — CHANGES_REQUESTED** [review]
These package versions will need to be updated again once they have been updated to include _assemblyMetadata.json_ as an embedded resource.

**Comment by semalaiappan** [comment]
Please ignore build failure for EdFi.Ods.Profiles.Sample (Packages) — TeamCity build failed

**Review by gmcelhanon — APPROVED** [review]

**Pull request merged**
